// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// VI_compute_Rcpp
double VI_compute_Rcpp(NumericVector c1, NumericVector c2, int K1, int K2);
RcppExport SEXP _WASABI_VI_compute_Rcpp(SEXP c1SEXP, SEXP c2SEXP, SEXP K1SEXP, SEXP K2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< int >::type K1(K1SEXP);
    Rcpp::traits::input_parameter< int >::type K2(K2SEXP);
    rcpp_result_gen = Rcpp::wrap(VI_compute_Rcpp(c1, c2, K1, K2));
    return rcpp_result_gen;
END_RCPP
}
// VI_Rcpp
NumericMatrix VI_Rcpp(NumericMatrix cls1, NumericMatrix cls2, NumericVector K1s, NumericVector K2s);
RcppExport SEXP _WASABI_VI_Rcpp(SEXP cls1SEXP, SEXP cls2SEXP, SEXP K1sSEXP, SEXP K2sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cls1(cls1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cls2(cls2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type K1s(K1sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type K2s(K2sSEXP);
    rcpp_result_gen = Rcpp::wrap(VI_Rcpp(cls1, cls2, K1s, K2s));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WASABI_VI_compute_Rcpp", (DL_FUNC) &_WASABI_VI_compute_Rcpp, 4},
    {"_WASABI_VI_Rcpp", (DL_FUNC) &_WASABI_VI_Rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_WASABI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
